FROM python:3.12-slim

WORKDIR /tests

COPY services/menu-service       ./menu-service
COPY services/warehouse-service  ./warehouse-service
COPY services/order-service      ./order-service
COPY services/auth-service       ./auth-service

RUN pip install --no-cache-dir \
      -r menu-service/requirements.txt \
      -r warehouse-service/requirements.txt \
      -r order-service/requirements.txt \
      -r auth-service/requirements.txt \
      aiosqlite

COPY run_tests.sh .
RUN chmod +x run_tests.sh

CMD ["./run_tests.sh"]